# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=30, unique=True, verbose_name='\u8d26\u53f7')),
                ('password', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('info', models.TextField(verbose_name='\u7b80\u4ecb')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=30, unique=True, verbose_name='\u8d26\u53f7')),
                ('fromhid', models.CharField(max_length=30, verbose_name='\u6765\u81ea\u54ea\u4e2a\u533b\u9662')),
                ('fromdid', models.CharField(max_length=30, verbose_name='\u6765\u81ea\u54ea\u4e2a\u533b\u751f')),
                ('tohid', models.CharField(max_length=30, verbose_name='\u8f6c\u5230\u54ea\u4e2a\u533b\u9662')),
                ('todid', models.CharField(max_length=30, verbose_name='\u8f6c\u5230\u54ea\u4e2a\u533b\u751f')),
                ('pid', models.CharField(max_length=30, verbose_name='\u6765\u81ea\u54ea\u4e2a\u60a3\u8005')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('info', models.TextField(verbose_name='\u8be6\u60c5')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('type', models.CharField(max_length=1, verbose_name='\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30, unique=True, verbose_name='\u8d26\u53f7')),
                ('password', models.CharField(max_length=30, verbose_name='\u5bc6\u7801')),
                ('name', models.CharField(max_length=30, verbose_name='\u59d3\u540d')),
                ('info', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('is_changing', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpt.Doctor')),
            ],
        ),
    ]
