# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pcnt',
            field=models.IntegerField(default=0, verbose_name='\u60a3\u8005\u6570'),
        ),
    ]
