# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpt', '0002_doctor_pcnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='extra',
            field=models.TextField(default='', verbose_name='\u9644\u52a0\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mid',
            field=models.CharField(max_length=30, verbose_name='\u8d26\u53f7'),
        ),
    ]
